# Change prefix from ctrl+b to ctrl+a (easier since a is closer to ctrl key)
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Enable mouse support
set -g mouse on

# Start numbering windows/panes at 1 (so they go from 1..-> instead of 0, more intuitive to do ctrl+a+number)
set -g base-index 1
setw -g pane-base-index 1

# Faster key response
set -sg escape-time 0

# True color support
set -g default-terminal screen-256color

# Change pane split keys to more intuitive (| for horizontal split, - for vertical split)
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Change ctrl+a+left/right to change windows instead of panes
unbind Left
unbind Right
bind Left  previous-window
bind Right next-window

# Vim-style pane navigation (ctrl+b+h/j/k/l)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Colors, use what you like
set -g window-style fg=colour245,bg=colour235
set -g window-active-style fg=colour250
set -g pane-border-style fg=colour235
set -g pane-active-border-style fg=colour39

# Reload config with ctrl+a+r
bind r source-file ~/.tmux.conf \; display "tmux conf reloaded"

# Move windows in the indexing with Ctrl+Shift+Left/Right
bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

# Enable vi keys in copy mode (ctrl+a [)
setw -g mode-keys vi
unbind-key -T copy-mode-vi v
bind-key -T copy-mode-vi 'v' send -X begin-selection		# Enable 'v' key (default SPACE)
bind-key -T copy-mode-vi 'C-z' send -X rectangle-toggle		# Enable visual block mode (C-z, then v)
bind-key -T copy-mode-vi 'y' send -X copy-selection			# Enable 'y' key (default ENTER)
