# Juuso Rinta 2026

# Change prefix from ctrl+b to ctrl+a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Render nvim correctly inside tmux
set -s default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

setw -g aggressive-resize on
set -g mouse on					# Enable mouse support

# Tmux forwards focus-gain/loss events to app running in pane,
# e.g. nvim's autoread actually works
set -g focus-events on
set -g history-limit 50000		# A bigger scrollback
set -g display-time 4000		# Display tmux messages 4s instead of 750ms
set -g status-interval 5		# Refresh status-left and right every 5s instead of 15

set -g base-index 1				# Start numbering windows/panes at 1
setw -g pane-base-index 1

set -g renumber-windows on		# Renumber windows on the fly when e.g. closing windows
set -sg escape-time 0			# Faster key response

bind r source-file ~/.tmux.conf \; display "tmux conf reloaded"

bind a last-window
bind b set-window-option synchronize-panes \; display "synchronize-panes toggled"
bind | split-window -h -c "#{pane_current_path}"	# Change pane split keys to more intuitive
bind - split-window -v -c "#{pane_current_path}"	# And open in CWD instead of home
unbind '"'
unbind %

# left/right change windows instead of panes
unbind Left
unbind Right
bind Left  previous-window
bind Right next-window

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind-key o command-prompt -p "send pane to:"  "join-pane -t '%%'"

# Move windows in the indexing with C + S + Left/Right
bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

setw -g mode-keys vi										# Enable vi keys in copy mode (ctrl+a [)
unbind-key -T copy-mode-vi v
bind-key -T copy-mode-vi 'v' send -X begin-selection		# Enable 'v' key (default SPACE)
bind-key -T copy-mode-vi 'C-z' send -X rectangle-toggle		# Enable visual block mode (C-z, then v)
bind-key -T copy-mode-vi 'y' send -X copy-selection			# Enable 'y' key (default ENTER)

# Colour/display settings
#	Storing some nerdfont separator characters:   
set -g window-status-separator ''
set -g status-style 'bg=colour234,fg=colour245'
set -g window-status-style 'bg=colour240,fg=colour245'		# Inactive tabs
set -g window-status-format '#[fg=colour234,bg=colour240]#[fg=colour245,bg=colour240] #I:#W #[fg=colour240,bg=colour234]'
set -g window-status-current-style 'fg=#000000 bg=#7aa2f7'	# Active tab
set -g window-status-current-format '#[fg=colour234,bg=#7aa2f7]#[fg=#000000,bg=#7aa2f7,nobold] #I:#W #[fg=#7aa2f7,bg=colour234]'
set -g pane-border-style fg=colour235
set -g pane-active-border-style 'fg=#7aa2f7'
set -g window-style bg=colour234
set -g status-left '#[fg=colour245,bg=colour0] #S #[fg=colour0,bg=colour234]'
set -g message-style 'bg=colour234,fg=colour158'
set -g status-right '#[fg=colour234,bg=colour0] #[fg=colour245,bg=colour0]#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}],}"#{=21:pane_title}" %H:%M %y-%m-%d'
