# Change brefix from ctrl+b to ctrl+a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Enable mouse support
set -g mouse on

# Start numbering windows/panes at 1
set -g base-index 1
setw -g pane-base-index 1

# Faster key response
set -sg escape-time 0

# True color support
set -g default-terminal screen-256color

# Easier pane splits
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

#unbind -T root Left
#unbind -T root Right
unbind Left
unbind Right
bind Left  previous-window
bind Right next-window

# Vim-style pane nav
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Colors
set -g window-style fg=colour245,bg=colour235
set -g window-active-style fg=colour250
set -g pane-border-style fg=colour235
set -g pane-active-border-style fg=colour39

# Reload config
bind r source-file ~/.tmux.conf \; display "tmux conf reloaded"

bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1
